# FINITE FIELD ARITHMETIC 
Paling dasar, sebelum group operation (point addition/point doubling)

In [1]:
#adopt untuk Guide to ECC h.48 pdf
_.<Z> = GF(2)[]
F.<z> = GF(2^8, modulus=Z^8+Z^4+Z^3+Z+1)

In [2]:
# #keterangan/ coba coba
# F.list()
# F.order()
# a = F.gen(); a #ini a dijadikan generator?

# a, a+a, a+a+a, a+a+a+a, a+0, a+1, a*4 #bisa ngitung banyak sekaligus!

In [3]:
#addition
(z^3+z^2+1)+(z^2+z+1)

z^3 + z

In [4]:
#subtraction
(z^3+z^2+1)-(z^2+z+1)

z^3 + z

In [5]:
#mult
(z^3+z^2+1)*(z^2+z+1) #ini dia auto hasil reduction.. gimana cara liat sebelum reduction?

z^5 + z + 1

In [56]:
z^7 * z^2

z^5 + z^4 + z^2 + z

In [6]:
#mult sebelum reduction, bisa liat dengan diubah jadi representasi polynom.
A = z^3+z^2+1
B = z^2+z+1


A_poly = A.polynomial()
B_poly = B.polynomial()
A_poly * B_poly


#Source:
# #https://ask.sagemath.org/question/38734/pre-reduction-multiplication-result-in-binary-field/
# X = Integer(0x009D73616F35F4AB1407D73562C10F);
# Y = Integer(0x00A52830277958EE84D1315ED31886);

# F.<x> = GF(2)[];
# p = x^113 + x^9 + 1;
# BF = GF(2^113, 'x', modulus=p);

# X_bf = BF._cache.fetch_int(X);
# Y_bf = BF._cache.fetch_int(Y);

# X_poly = X_bf.polynomial()
# Y_poly = Y_bf.polynomial()
# X_poly * Y_poly

z^5 + z + 1

In [7]:
#inversion
(z^3+z^2+1)^-1

z^7 + z^6 + z^5 + 1

# GROUP OPERATION (SKIP AJA LANGSUNG KE BAWAHNYA)

In [8]:
#coba ulang pake yg dr certicom
#https://www.certicom.com/content/certicom/en/41-an-example-of-an-elliptic-curve-group-over-f2m.html
#adopt untuk Guide to ECC h.48 pdf
# g = F.gen(1)

In [9]:
# ##curve25519
# def findBasepoint(prime, A):
#        F = GF(prime)
#        E = EllipticCurve(F, [0, A, 0, 1, 0])

#        for uInt in range(1, 1e3):
#          u = F(uInt)
#          v2 = u^3 + A*u^2 + u
#          if not v2.is_square():
#            continue
#          v = v2.sqrt()
#          point = E(u, v)
#          pointOrder = point.order()
#          if pointOrder > 8 and pointOrder.is_prime():
#             Q=u^3 + A*u^2 + u
#             return u, Q, sqrt(Q), point

# res=findBasepoint(2^255 - 19, 486662)
# res

In [10]:
F.inject_variables()

Defining z


In [11]:
R.<x,y> = F[]; R #ga nyambung ke yg setelahnya atau ke yg sebeluumnya sih

Multivariate Polynomial Ring in x, y over Finite Field in z of size 2^8

In [12]:
C = EllipticCurve(y^2+x*y-x^3-x^2-1) ; C #y^2 + xy = x^3 + ax^2 + b, a elemen F_2 ([0,1]) , b elemen F_2^n * (extension field kan ya?) --> misal a = b =1?

Elliptic Curve defined by y^2 + x*y = x^3 + x^2 + 1 over Finite Field in z of size 2^8

In [13]:
C.points()

[(0 : 1 : 0), (0 : 1 : 1), (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1), (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1), (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + 1 : 1), (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + z : 1), (z^2 + 1 : z^4 + z : 1), (z^2 + 1 : z^4 + z^2 + z + 1 : 1), (z^3 : z^5 : 1), (z^3 : z^5 + z^3 : 1), (z^3 + 1 : z^7 + z^5 + z + 1 : 1), (z^3 + 1 : z^7 + z^5 + z^3 + z : 1), (z^3 + z^2 : z^7 + z^6 + z^5 + 1 : 1), (z^3 + z^2 : z^7 + z^6 + z^5 + z^3 + z^2 + 1 : 1), (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^2 + z : 1), (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^3 + z + 1 : 1), (z^3 + z^2 + z : z^7 + z^4 : 1), (z^3 + z^2 + z : z^7 + z^4 + z^3 + z^2 + z : 1), (z^4 + 1 : z^3 + z^2 + z : 1), (z^4 + 1 : z^4 + z^3 + z^2 + z + 1 : 1), (z^4 + z : z^7 + z^5 + z^3 + z^2 : 1), (z^4 + z : z^7 + z^5 + z^4 + z^3 + z^2 + z : 1), (z^4 + z + 1 : z^7 + z^6 + z^5 + z : 1), (z^4 + z + 1 : z^7 + z^6 + z^5 + z^4 + 1 : 1), (z^4 + z^2 + z + 1 : z^7 + z : 1), (z^4 + z^2 + z + 1 : z^7 + z^4 + z^2 + 1 : 1), (z^4 + z^

In [14]:
C.order()

288

In [15]:
# https://ask.sagemath.org/question/9976/elliptic-curves/
#     ini yg gede banget p^163... real...

In [16]:
# G = C.point(()) 
pts = [p for p in C.points()] #AAAh ada 16 sedangkan di certicom 15, karena 1nya (pts[0]) itu point at infinity!!
# pts
# for i in len(pts):
#     print(i, pts[i])

In [17]:
pts[5]+pts[3]

(z^3 + 1 : z^7 + z^5 + z + 1 : 1)

In [18]:
C.gens() #For extension fields, the generator is obtained with the .gen() function. 
#nilai ini ga berubah2, artinya memang dia ya yg memenuhi?

((z^7 + z^6 + z^4 + z^3 + z + 1 : z^7 + z^5 + z : 1),
 (z^6 + z^5 + z^3 + z^2 : z^6 + z^4 + z^3 + z^2 + 1 : 1))

In [19]:
pts[5]+pts[5] #point addition

(z^6 + z^4 + z^2 + z + 1 : z^6 + z^5 + z^2 : 1)

In [20]:
2*(pts[5]) #doubling

(z^6 + z^4 + z^2 + z + 1 : z^6 + z^5 + z^2 : 1)

In [21]:
#misal, titik yg mau ditambah:
pts[2], pts[3], pts[2]+pts[3] #ups jadi point at inf, ganti yuuu

((1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1),
 (0 : 1 : 0))

In [22]:
pts[1], pts[2], pts[1]+pts[2] # ini enak kayanya bucat diplot di QC? cek requirement 
#P(x1, y1)= (0,1), Q(x2, y2) = (1, z^3 + z^2), R = (1, z^3 + z^2 + 1) --> so far masih sesuai syarat sih, x1 != x2. Dan yg ditambahin, si const pake yg agak rebek biar ga terlalu trivial.. gt? 

((0 : 1 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1))

In [23]:
#fail
# plot(pts[1]) #gabisa diplot karena yaa polynom. That's why si certicom dibuat g^0 g^1 dkk, biar representingnya enak!(kayanya)

In [24]:
pts[2]

(1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1)

In [25]:
type(pts[2])

<class 'sage.schemes.elliptic_curves.ell_point.EllipticCurvePoint_finite_field'>

In [26]:
pts[2][1]+pts[1][1], pts[2][1]+pts[2][1]

(z^7 + z^5 + z^4 + z^3 + z^2 + 1, 0)

In [27]:
pts[2][1]

z^7 + z^5 + z^4 + z^3 + z^2

In [28]:
pts[2][1]


z^7 + z^5 + z^4 + z^3 + z^2

In [29]:
C.random_element()

(z^6 + z^5 + z^3 + z^2 : z^5 + z^4 + 1 : 1)

In [30]:
list(C)

[(0 : 1 : 0),
 (0 : 1 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1),
 (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + 1 : 1),
 (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + z : 1),
 (z^2 + 1 : z^4 + z : 1),
 (z^2 + 1 : z^4 + z^2 + z + 1 : 1),
 (z^3 : z^5 : 1),
 (z^3 : z^5 + z^3 : 1),
 (z^3 + 1 : z^7 + z^5 + z + 1 : 1),
 (z^3 + 1 : z^7 + z^5 + z^3 + z : 1),
 (z^3 + z^2 : z^7 + z^6 + z^5 + 1 : 1),
 (z^3 + z^2 : z^7 + z^6 + z^5 + z^3 + z^2 + 1 : 1),
 (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^2 + z : 1),
 (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^3 + z + 1 : 1),
 (z^3 + z^2 + z : z^7 + z^4 : 1),
 (z^3 + z^2 + z : z^7 + z^4 + z^3 + z^2 + z : 1),
 (z^4 + 1 : z^3 + z^2 + z : 1),
 (z^4 + 1 : z^4 + z^3 + z^2 + z + 1 : 1),
 (z^4 + z : z^7 + z^5 + z^3 + z^2 : 1),
 (z^4 + z : z^7 + z^5 + z^4 + z^3 + z^2 + z : 1),
 (z^4 + z + 1 : z^7 + z^6 + z^5 + z : 1),
 (z^4 + z + 1 : z^7 + z^6 + z^5 + z^4 + 1 : 1),
 (z^4 + z^2 + z + 1 : z^7 + z : 1),
 (z^4 + z^2 + z + 1 : z^7 + z^4 

In [31]:
pts[2][1]

z^7 + z^5 + z^4 + z^3 + z^2

# REFERENCE UNTUK QC

In [32]:
#coba 
# ala ala standar, a mostly 1 or 0, b mostly 1. Samain aja! h. 286 Guide to ECC (Tabel A.4)


# #####################
# #Ini sama aj aky yg bawah tp ga nempel akunya, mending cara aku aja
# b =  0x1
# ZZ.<x>=GF(2)[]
# K.<a>=GF(2^8,'x',modulus=x^8+x^4+x^3+x+1)
# bb=ZZ(b.digits(2))
# E=EllipticCurve(K,[1,1,0,0,bb]) #ininya bener segini? kl ini a nya 0 ya? coba a nya 1? --> gabisa, jadi singular curve....

# # P=E.random_element()
# # print(P[0])
# # print(P[1])
# # print(E.is_on_curve(P[0],P[1]))  # OK


# ##########################

# WORKING!!
# GF?
F.<x> = GF(2)[]
# K.<a> = GF(2**8, name='a', modulus="primitive") #hasilnya: x^8 + x^4 + x^3 + x^2 + 1
K.<z> = GF(2**8, name='z', modulus=x^8 + x^4 + x^3 + x + 1) #kita pake yg sesuai Bernstein aja
K.inject_variables() #gapake ini jg bisa, tapi ada bahasan di asksage hrs pake ini untuk irred polynom (?) atau apa gt
f = K.modulus(); f

Defining z


x^8 + x^4 + x^3 + x + 1

In [33]:
# # EllipticCurve?
# y^2 + a_1 xy + a_3 y = x^3 + a_2 x^2 + a_4 x + a_6. #"EllipticCurve([a1,a2,a3,a4,a6])" 
#case binary: y^2 + xy = x^3 +ax^2 + b; a [0,1] pilih 1, b pilih 1 (biasa angka segitu, atau 1nya 0 1nya 1)
#jadi case kita [a1=1,a2=a=1,a3=0,a4=0,a6=b=1]
E = EllipticCurve(K,[1,1,0,0,1]); E #alhamdulillaah

Elliptic Curve defined by y^2 + x*y = x^3 + x^2 + 1 over Finite Field in z of size 2^8

In [34]:
E.order()

288

In [35]:
print(E.points()[:20])

[(0 : 1 : 0), (0 : 1 : 1), (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1), (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1), (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + 1 : 1), (z + 1 : z^7 + z^6 + z^5 + z^4 + z^3 + z^2 + z : 1), (z^2 + 1 : z^4 + z : 1), (z^2 + 1 : z^4 + z^2 + z + 1 : 1), (z^3 : z^5 : 1), (z^3 : z^5 + z^3 : 1), (z^3 + 1 : z^7 + z^5 + z + 1 : 1), (z^3 + 1 : z^7 + z^5 + z^3 + z : 1), (z^3 + z^2 : z^7 + z^6 + z^5 + 1 : 1), (z^3 + z^2 : z^7 + z^6 + z^5 + z^3 + z^2 + 1 : 1), (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^2 + z : 1), (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^3 + z + 1 : 1), (z^3 + z^2 + z : z^7 + z^4 : 1), (z^3 + z^2 + z : z^7 + z^4 + z^3 + z^2 + z : 1), (z^4 + 1 : z^3 + z^2 + z : 1), (z^4 + 1 : z^4 + z^3 + z^2 + z + 1 : 1)]


In [36]:
E.cardinality() #== # len(C.points()) == jumlah point, including point at inf (O)
#case ini sama dengan E.order(), tapi lupa teorinya, mungkin karena cofactor = 1 (?)

288

In [37]:
# [ p for p in E.points() if (p.order() < 10) ] #untuk ngelist point2 yang ada, under 10
# [ (p.order(), p) for p in E.points() if (p.order() < 10) ] #sekalian di list ordernya
# sorted([ (p.order(), p) for p in E.points() if (p.order() < 10) ]) #ordernya versi sorted sekalian

sorted([ (p.order(), p) for p in E.points()])

[(1, (0 : 1 : 0)),
 (2, (0 : 1 : 1)),
 (3, (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^2 + z : 1)),
 (3, (z^3 + z^2 + 1 : z^6 + z^5 + z^4 + z^3 + z + 1 : 1)),
 (3, (z^6 + z^4 + 1 : z^7 + z^4 + z^3 + 1 : 1)),
 (3, (z^6 + z^4 + 1 : z^7 + z^6 + z^3 : 1)),
 (3, (z^7 + z^5 + z^4 + 1 : z^6 + z^5 + z^4 + 1 : 1)),
 (3, (z^7 + z^5 + z^4 + 1 : z^7 + z^6 : 1)),
 (3, (z^7 + z^6 + z^5 + z^3 + z^2 : z^5 + z^4 + 1 : 1)),
 (3, (z^7 + z^6 + z^5 + z^3 + z^2 : z^7 + z^6 + z^4 + z^3 + z^2 + 1 : 1)),
 (4, (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1)),
 (4, (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1)),
 (6, (z^6 + z^4 + z^3 + z^2 : z^7 + z^5 + z^4 + z^3 + z^2 + z : 1)),
 (6, (z^6 + z^4 + z^3 + z^2 : z^7 + z^6 + z^5 + z : 1)),
 (6, (z^6 + z^4 + z^3 + z^2 + 1 : z^7 + z^5 + z^3 + z^2 : 1)),
 (6, (z^6 + z^4 + z^3 + z^2 + 1 : z^7 + z^6 + z^5 + z^4 + 1 : 1)),
 (6, (z^7 + z^6 + z^5 : z^6 + z^4 + z^3 + 1 : 1)),
 (6, (z^7 + z^6 + z^5 : z^7 + z^5 + z^4 + z^3 + 1 : 1)),
 (6, (z^7 + z^6 + z^5 + 1 : z^6 + z^2 + z + 1 : 1)),
 (6, (z^7 +

In [38]:
E.gens() #ini generator point-nya? Ada 2--> gak juga ya, ini cari yg lower order aja (?) #see https://www.johannes-bauer.com/compsci/ecc/

#(z^7 + z^6 + z^4 + z^3 + z + 1 : z^7 + z^5 + z : 1) dan
#(z^6 + z^5 + z^3 + z^2 : z^6 + z^4 + z^3 + z^2 + 1 : 1)

((z^7 + z^6 + z^4 + z^3 + z + 1 : z^7 + z^5 + z : 1),
 (z^6 + z^5 + z^3 + z^2 : z^6 + z^4 + z^3 + z^2 + 1 : 1))

In [39]:
# P = E.point((1, z^7 + z^5 + z^4 + z^3 + z^2)) #pilih salah 1 dari point yg atas #orde 4
P = E.point((z^7 + z^5 + z^4 + z^3 + z^2 + 1, z^7 + z^5 + z^4 + z^3 + z^2)) #orde 8
P.order()

8

In [40]:
p = [ P * x for x in range(P.order()) ] #p = pts = point
p #len == 8 == order

#analisis point2 yg mungkin dipake untuk simulasi
# kesimpulan sementara: yg 
# [(0 : 1 : 0), #O, no
#  (z^7 + z^5 + z^4 + z^3 + z^2 + 1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1), #x != y, OK
#  (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1), #x-nya 1, gapapa?
#  (z^7 + z^5 + z^4 + z^3 + z^2 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1), #x != y, tapi cerminan dari poin pertama.. udah rapopo la
#  (0 : 1 : 1), # x=0... susah nanti kl ada division dkk (?) gak juga sih kali ya (?)
#  (z^7 + z^5 + z^4 + z^3 + z^2 : 1 : 1), #y-nya 1, gapapa?
#  (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
#  (z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1 : 1)]

[(0 : 1 : 0),
 (z^7 + z^5 + z^4 + z^3 + z^2 + 1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1),
 (z^7 + z^5 + z^4 + z^3 + z^2 : z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1),
 (0 : 1 : 1),
 (z^7 + z^5 + z^4 + z^3 + z^2 : 1 : 1),
 (1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1),
 (z^7 + z^5 + z^4 + z^3 + z^2 + 1 : 1 : 1)]

yaudah pokoknya poin 1 ke poin lain aja dulu yg dicoba!! BESOK 27 APRIL COBA INI YESSS

In [41]:
p[1] #ambil ini aja yaa sebagai P1 (x1, y1) = (z^7 + z^5 + z^4 + z^3 + z^2 + 1, z^7 + z^5 + z^4 + z^3 + z^2 )

(z^7 + z^5 + z^4 + z^3 + z^2 + 1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1)

In [42]:
p[5] #coba sebagai P2 (x2, y2) = (z^7 + z^5 + z^4 + z^3 + z^2, 1 )

(z^7 + z^5 + z^4 + z^3 + z^2 : 1 : 1)

In [43]:
res = p[1] + p[5]
res #ok P3 (x3, y3) = (1 , z^7 + z^5 + z^4 + z^3 + z^2)

(1 : z^7 + z^5 + z^4 + z^3 + z^2 : 1)

In [44]:
EllipticCurve?


# CEK CEK PYTHON BIASA

In [45]:
#tetep pake Sage tapi di level finite field arithmetic (one level lower)
P1 = (z^7 + z^5 + z^4 + z^3 + z^2 + 1, z^7 + z^5 + z^4 + z^3 + z^2 )
P2 = (z^7 + z^5 + z^4 + z^3 + z^2, 1)

x1 = P1[0]
y1 = P1[1]

x2 = P2[0]
y2 = P2[1]

In [46]:
#ADDITION
#x3

slope = (y1 + y2) / (x1 + x2)
x3 = pow(slope, 2)+ slope + x1 + x2 + 1 # a = 1
y3 = (x2 + x3) * slope + x3 + y2
print (x3,y3)  #1 z^7 + z^5 + z^4 + z^3 + z^2 --> x3 salah, tapi y3 bener?? --> pake manual (ga pow) pun hasilnya sama!
print(res[0] == x3, res[1] == y3) #bandingkan dengan hitung langsung pake Sage, bener!

1 z^7 + z^5 + z^4 + z^3 + z^2
True True


In [47]:
#DOUBLING
#x3
slope = (y1 + y2) / (x1 + x2)
x3 = pow(slope, 2)+ slope + 1 # a = 1
y3 = pow(x1, 2) + (slope+1)* x3
print (x3,y3)  #0 z^7 + z^5 + z^4 + z^3 + z^2 --> --> karena ini doubling...--> pake manual (ga pow) pun hasilnya sama!


#x3 tanpa pow
# slope = (y1 + y2) / (x1 + x2)
# x3 = slope**2+ slope + 1 # a = 1
# y3 = x1**2 + (slope+1)* x3
# print (x3,y3)  #0 z^7 + z^5 + z^4 + z^3 + z^2 --> karena ini doubling...

0 z^7 + z^5 + z^4 + z^3 + z^2


## Sekarang di run per step/flow (untuk cek correctness

In [48]:
#ROW 1 (Register x1)
step1 = x1+x2

step2 = step1



In [49]:
#ROW 3 (Register y1)




In [50]:
#ROW 4 (Register 0)


#ROW 2 (qubit q)


In [51]:
#ini ga kepake sih

import random
deg = 8
temp = random.randrange(1,(2**deg))
# b = bin(temp)[2:]
# b
temp

238

## CEK CEK paper ETRI

In [52]:
# Python program to inverse
# a matrix using numpy

# Import required package
import numpy as np
from scipy import linalg

# Taking a 8 * 8 matrix
A = np.array([[1, 0, 1, 0, 0, 0, 0, 0],  #array diganti jadi matrix, tetep hasilnya sama ternyata
            [1, 0, 1, 0, 1, 1, 0, 0],
            [1, 1, 0, 1, 0, 0, 1, 0],
            [0, 1, 1, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 1, 0, 0],
            [1, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 1, 1, 0],
            [0, 1, 1, 1, 0, 0, 0, 1]]) #arraynya multiplier ETRI

print(A)


# Calculating the inverse of the matrix
print(np.linalg.inv(A))

print(np.linalg.det(A))

# -NOTE: HASIL INVERSE MASIH SALAH
#     - MAU CEK UNITARY BLM BISA --> di qiskit aja kali ya meh gancang (kok lu mager/reluctant banget sih buat open vscode atau qiskit..)

[[1 0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0 0]
 [1 1 0 1 0 0 1 0]
 [0 1 1 1 0 0 0 0]
 [0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 1]]
[[ 1.  0.  1. -1.  0. -1.  0.  0.]
 [ 1.  0.  2. -1. -1. -3.  1.  0.]
 [ 0.  0. -1.  1.  0.  1.  0.  0.]
 [-1.  0. -1.  1.  1.  2. -1.  0.]
 [-2.  1. -1.  1.  0.  2. -1.  0.]
 [ 1.  0.  1. -1.  0. -2.  1.  0.]
 [-1.  0. -1.  1.  0.  2.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  1.]]
1.0


In [53]:
bb = np.array([[1],[0], [1], [0], [1], [0], [1], [0]])

# bb.dot(A)

A.dot(bb)

# A.ndim

array([[2],
       [3],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1]])

In [54]:
bb = np.array([[1],[0], [1], [0]])

A = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0]])

A.dot(bb)


array([[1],
       [0],
       [0],
       [1]])

In [55]:
#coba CNOT

A = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0]])

print(np.linalg.inv(A)) #--> bener.... yg atas kl ada angka 2 nya... ga unitary??


apakah matrixnya harus ukuran 16?? kan 2n??

itu mappingnya gt ya..
EMANG GA UNITARY!! MAKANYA MAU DIBIKIN GIMANA JADI UNITARY!! KAN MODULAR WEEY!!!!!

SyntaxError: invalid syntax (<ipython-input-55-22260d53d678>, line 13)

# REF AWAL DARI INTERNET

In [ ]:
#salin

#https://ask.sagemath.org/question/8736/nist-b-283-elliptic-curve/
b =  0x027B680AC8B8596DA5A4AF8A19A0303FCA97FD7645309FA2A581485AF6263E313B79A2F5
Z.<x>=GF(2)[]
K.<a>=GF(2^283,'a',modulus=x^283 + x^12 + x^7 + x^5 + 1)
bb=Z(b.digits(2))
E=EllipticCurve(K,[1,1,0,0,bb]) 
P=E.random_element()
print(P[0])
print(P[1])
print(E.is_on_curve(P[0],P[1]))  # OK

# I was not able  to compute the order
# print E.order()   exhausts memory and exits

